import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { I18nProviderClient } from '~/core/locales/client';
import { ReactElement } from 'react';
import NavigationElements from '~/components/NavigationElements';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  params: { locale },
  children,
}: {
  params: { locale: string };
  children: ReactElement;
}) {
  return (
    <html lang={'en'} className={'h-full bg-white'}>
      <body className={`h-full ${inter.className}`}>
        <I18nProviderClient locale={locale}>
          <NavigationElements>{children}</NavigationElements>
        </I18nProviderClient>
      </body>
    </html>
  );
}
