import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { I18nProviderClient } from '~/core/locales/client';
import React, { ReactElement } from 'react';
import NavigationElements from '~/components/NavigationElements';
import AudioPlayer from '~/components/AudioPlayer';
import { PlayingAudioProvider } from '~/components/AudioPlayer/utils/PlayingAudioContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  params: { locale },
  children,
}: {
  params: { locale: string };
  children: ReactElement;
}) {
  return (
    <html lang={'en'} className={'h-screen bg-white'}>
      <body className={`h-screen ${inter.className}`}>
        <I18nProviderClient locale={locale}>
          <NavigationElements>
            <PlayingAudioProvider>
              <div className={'flex h-full flex-col justify-between'}>
                {children}
                <AudioPlayer />
              </div>
            </PlayingAudioProvider>
          </NavigationElements>
        </I18nProviderClient>
      </body>
    </html>
  );
}
